### ISSUE TITLE
portable data set for json5 parser

### ISSUE THREAD

**Issue by rlidwka** [rlidwka/jju#11]
In yaml format, maybe something like this:

``` yaml

---
name: test
description: blahblah
input: {foo: 'bar'}
output: {"foo":"bar"}

---
name: test2
description: blah-blah
input: {'foo': 'bar'}
output: {"foo":"bar"}
```

where `output` is `JSON.stringify(JSON5.parse(input))`
